### ISSUE TITLE
Translation feature

### ISSUE THREAD

**Issue by Airon90** [audreyt/ethercalc#11]
Is it possible to make Ethercalc translatable?
You can sniff the language through user agent or add an option to settings

**Comment by audreyt** [comment]
This is now being worked on in the `l10n/` directory with `zh-TW.json` as the first example.

**Comment by cbrunet** [comment]
How is the translations file loaded? I did not see anything about that...

**Comment by audreyt** [comment]
It's not currently loaded automatically — `index.html` line 110 has a hard-coded test for `zh-TW` only. Pull reqs welcome!

**Comment by cbrunet** [comment]
Thank you for your quick answer! I wanted to be sure nobody already did it before beginning working on this.

I almost have a working prototype now. Just a few questions before preparing the pull request:

1. Should I load the json file from `socialcalcconstants.js` instead of from the index.html file?
2. Do you want to keep default values for constants in `socialcalcconstants.js`, or do you want to replace them with values from `en.json`? What I would propose would be to load values from `navigator.language`.json, and if the language file is not found, then to load values from `en.json` as fallback. In that case, all constants could be removed from `socialcalcconstants.js`.
3. When I modify index.html, how can I clear the cache? Actually, the only way I found is to create a new sheet each time I want to test a modification... Otherwise, I only see the old index.html file.

**Comment by audreyt** [comment]
1. Both works — index.html is arguably simpler.
2. That sounds great!
3. `make manifest` would clean the cache.
