### ISSUE TITLE
socialcalc save format 

### ISSUE THREAD

**Issue by SheetJSDev** [audreyt/ethercalc#114]
I'm looking for more details on the socialcalcsave format.  Threw together a [really basic parser](https://github.com/SheetJS/js-harb/blob/master/bits/70_socialcalc.js), but there are lots of details missing.  Do you recommend any sources?

On a side note, j version 0.4.0 works with the module to provide basic socialcalc read support, allowing for XLSX export:

```
$ curl https://ethercalc.org/_/x9aetnquyh | j -X -o test.xlsx # generates test.xlsx
```

**Comment by atifaziz** [comment]
The link into `socialcalc-3.js` in the [previous comment](https://github.com/audreyt/ethercalc/issues/114#issuecomment-58741982) is broken since PR #363 was merged and SocialCalc sources were removed from the repo. Below is a revised link that should never go bad as it is pinned to 0541a4218f6df856a2373fd98637bd60ce73607d, which is the commit prior to merging of PR #363:

[Lines 366-443 of `socialcalc-3.js`](https://github.com/audreyt/ethercalc/blob/0541a4218f6df856a2373fd98637bd60ce73607d/socialcalc-3.js#L366-L443)
