### ISSUE TITLE
List existing spreadsheets?

### ISSUE THREAD

**Issue by Yaco** [audreyt/ethercalc#124]
Hi!,
is it possible to get a list of the existing sheets? Is it possible to show that in ethercalc's frontpage?

**Comment by gawel** [comment]
For those interested, I have a docker-compose.yml with a custom start page with a list of rooms using the /_rooms url https://github.com/bearstech/bearcalc

**Comment by eddyparkinson** [comment]
/_roomlinks is also available - html links to each room

**Comment by amir-zeldes** [comment]
@eddyparkinson I really like the /_roomlinks, it's very useful, thanks for pointing it out! 

Is there also a way to get a list of active rooms, as in a list of sheets that are actually communicating with users at the moment?

**Comment by eddyparkinson** [comment]
>active rooms
Am sure such a list of active rooms could be added. Maybe sort rooms by date changed.

**Comment by amir-zeldes** [comment]
Thanks for the quick reply! How hard do you think this would be to implement? Ideally I'd also like to see most recent edit time for each room. 

If you think it's something I might be able to implement and you point me in the right direction, I might be able to do it.

**Comment by eddyparkinson** [comment]
It would need a timestamp adding, I think in this section of code https://github.com/audreyt/ethercalc/blob/master/src/sc.ls#L201

The timestamp could be sorted as a new item in the DB or as part of the snapshot.

And then create something to read and print out.
this is the roomlinks code:
https://github.com/audreyt/ethercalc/blob/master/src/main.ls#L231

**Comment by amir-zeldes** [comment]
Hi @eddyparkinson , thanks for pointing this out! I must admit, I don't really know LiveScript, but I'm happy to give it a try. I modified the code as follows in `sc.ls`:

```
     <~ DB.multi!
        .set "snapshot-#room" newSnapshot
        .set "timestamp-#room" Date.now()
        .del "log-#room"
        .bgsave!
        .exec!
```

And then defined the call in `main.ls` as:

```
  if @CORS
     @get '/_roomtimes' : ->
        @response.type Text
        return @response.send 403 '_roomtimes not available with CORS'
  else
     @get '/_roomtimes' : ->
        rooms <~ SC._rooms 
        roomtimes = for room in rooms
          DB.get "timestamp-#room"
        @response.type Html
        @response.json 200 roomtimes
```

I then tried editing a document and retrieving _roomtimes, and what I get is a json array like this:
```
[ true, true, true, true, true, ... ]
```

No document record is showing a timestamp-#room value. So it seems the call is defined, but I am either not storing Date.now() correctly, or my call is not accessing it correctly. Any ideas? I apologize again for my ignorance about LiveScript!

**Comment by amir-zeldes** [comment]
Hi again - I had some time to look at it again today, and I can confirm that the UTC timestamp is being saved to redis. I can get it fine from redis-cli:

```
127.0.0.1:6379> GET timestamp-some_spreadsheet
"1498675812754"
```

So that is being stored as a string. But for some reason the return value of DB.get is a boolean in: 

```
        roomtimes = for room in rooms
          DB.get "timestamp-#room"
```

I thought maybe I was misunderstanding the comprehension, so I tried just pushing the typeof of the return value into an array, but it seems it's really a boolean:

```
     @get '/_roomtimes' : ->
        rooms <~ SC._rooms
        roomtimes = []
        for room in rooms
          time = DB.get "timestamp-#room"
          roomtimes.push typeof time
        @response.type Html
        @response.json 200 roomtimes
```

The result is [boolean, boolean, ...]

I also tried variants with `DB.multi!get("timestamp-#room").exec`, thinking maybe I'm getting a tuple containing an 'ok' result, as in (true, "UTC12345"), but that doesn't seem to work. Any tips on how to just get back the string for the redis key I'm setting in `sc.ls`? I must be missing something here...

**Comment by eddyparkinson** [comment]
**SC._roomtimes**

To get the list of roomtimes, suggest you add a function to /src/sc.ls
Look at SC._rooms and SC._get

**SC._rooms**

there is a function already a function SC._rooms
that gets the rooms. It is used in your code:


```
@get '/_roomtimes' : ->
        rooms <~ SC._rooms

```
here https://github.com/audreyt/ethercalc/blob/master/src/sc.ls#L112-L116


**SC._get**
it gets values from the db, you would need the values

see 
https://github.com/audreyt/ethercalc/blob/master/src/sc.ls#L89-L94

**Comment by amir-zeldes** [comment]
OK, so, since SC._get seems to be hardwired to give back snapshot-#room, I made a parallel function SC._time hardwired to get the timestamp of a room like this:

```
  SC._time = (room, cb) ->
    (, [x]) <~ DB.multi!
       .get "timestamp-#room"
       .exec!
       cb x
```

Then I call that function here by retrieving all snapshot keys and collecting corresponding timestamps with my new function:

```
  SC._roomtimes = (cb) ->
    (, [rooms]) <~ DB.multi!
       .keys \snapshot-*
       .exec!
    res = []
    for room in rooms
       time = SC._time room
       res.push time
    cb res

```

But again, this returns [true, true, ...]

It seems like whenever I call DB.get on the timestamp key, I get a boolean back. I can't figure out why my function is behaving differently from SC._get - how can I make `.get "timestamp-#room"` return the string, rather than `true`?

**Comment by eddyparkinson** [comment]
Suggest you use "console.log" to debug it. 

You can use http://livescript.net/ to paste livescript and see the JS


**issue 1**
This code

```
 SC._roomtimes = (cb) ->
    (, [rooms]) <~ DB.multi!
       .keys \snapshot-*
       .exec!
    res = []
    for room in rooms
       time = SC._time room
       res.push time
    cb res

```
looks to set  rooms = [snapshot-roomname1,snapshot-roomname2,...]
You can use SC._rooms to get this list of rooms.

**Issue 2**
watch the callback

`       time = SC._time room
`
does not pass a callback function

**Comment by amir-zeldes** [comment]
Thanks again for these tips! The compiler and logging to the command line helped me to figure a few things out, but I'm not quite there yet it seems... 

@get '/_roomtimes' in main.ls seems to be working fine - I can get it to return and print an arbitrary array as an API call, so that's good.

The SC._time function is also working correctly based on console logger output, since it retrieves correct UTC entries for each spreadsheet, or null if it hasn't been accessed since timestamp-saving was introduced. I can easily catch the null like this:

```
  SC._time = (room, cb) ->
    console.log "Getting time for #room"
    (, [x]) <~ DB.multi!
       .get "timestamp-#room"
       .exec!
       if x == null
         y = "--"
       else
         y = x
       console.log y  # This prints the correct UTC time for all documents
       cb y
```

But now I've hit a wall, which I think has to do with some sort of closure issue. Even though the log indicates that each timestamp is retrieved in sequence, I can't construct and persist an array to hold all of them. I can hold one of them and pass it on successfully as a callback, or I can iterate as many times as I have records, but then I'll get nulls. 

I've tried to implement a callback with closure based on some CoffeeScript examples I've found, but it doesn't seem to work. I've tried defining an anonymous function with do() ->, or enclosing either the room or the results array, but this doesn't seem to work. 

My final thought was to push functions rather than strings into the array and send the whole thing back as `cb`, but this doesn't seem to work either. Somehow I can't seem to get block closure inside the rooms loop such that the array defined outside the loop persists the results, even though the logger inside SC._time indicates that the timestamps are being retrieved. This is where I am now: 

```
  SC._roomtimes = (cb) ->
    console.log "Looking for roomtimes"
    rooms <~ SC._rooms
    console.log "got rooms: #rooms"  # Works
    res = []
    for room in rooms
       console.log "trying #room"  # Works
       f = (room) ->
          console.log "room in f is #room"
          x = SC._time room
          console.log "x is #x"  # Not working, even though the SC._time logger shows the time
       res.push f
    cb res
```

I appreciate your help and apologize again for my lacking understanding of LiveScript!

**Comment by amir-zeldes** [comment]
I forgot to say, I also tried a list comprehension like this:

`res <~ [SC._time(room) for room in rooms]`

And based on a CoffeeScript example, something like this:

`res <~ ((SC._time(room) for room in rooms)...)`

But that won't compile...

**Comment by eddyparkinson** [comment]
You could use HSET and HGETALL

```
redis> HSET myhash field1 "Hello"
(integer) 1
redis> HGET myhash field1
"Hello"
redis> HSET myhash field3 "Hello3"
(integer) 1
redis> hgetall myhash
1) "field1"
2) "Hello"
3) "field3"
4) "Hello3"
redis> HSET myhash field1 "Hello remove"
(integer) 0
redis> hgetall myhash
1) "field1"
2) "Hello remove"
3) "field3"
4) "Hello3"
redis> 

```
Live demo:
https://redis.io/commands/hset


This would be simpler and remove the call back issue.

e.g. hset and hgetall
https://github.com/audreyt/ethercalc/blob/master/src/sc.ls#L239
https://github.com/audreyt/ethercalc/blob/master/src/sc.ls#L236


**Call back**
these can be hard, as the execution flow is not always what you first think it is.

**Comment by amir-zeldes** [comment]
Yes, this works! This also looks much simpler, and since .hgetall returns an array in one go, there's no loop scope issue. Perfect!

This is what I have:

```
  SC._roomtimes = (cb) ->
    (_, res) <~ DB.hgetall "timestamps"
    cb res
```

And:
```
      w._snapshot = newSnapshot
      <~ DB.multi!
        .set "snapshot-#room" newSnapshot
        .hset \timestamps "timestamp-#room" (Date.now() + "_" + room)
        .del "log-#room"
        .bgsave!
        .exec!
```

Shall I do a pull request to audreyt/ethercalc ?

**Comment by amir-zeldes** [comment]
@audreyt : which branch should I make the pull request to?

**Comment by audreyt** [comment]
`master` will do. Some instances (publicly hosted) may not wish to expose this endpoint, but that's OK, we can add a flag.

**Comment by eddyparkinson** [comment]
Just a thought, add something like this?

https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sort_table

**Comment by amir-zeldes** [comment]
That's right, I forgot you'd mentioned sorting. I added reverse sorting by UTC (latest first):

amir-zeldes/ethercalc@e0c220a32022a263aecc4229b02d944857123358

**Comment by audreyt** [comment]
Released as `ethercalc@0.20170704.0` on npm. Thanks for the contribution!

**Comment by kevev** [comment]
I tweaked gawel's code that lists links to each of the spreadsheets on the main page. I adjusted the font and center aligned the list.  :)



[start.html.txt](https://github.com/audreyt/ethercalc/files/1662418/start.html.txt)
[start.js.txt](https://github.com/audreyt/ethercalc/files/1662419/start.js.txt)

**Comment by mayeulk** [comment]
If you run ethercalc in a Docker container, using a container named redis for storage, this is a one-liner to get the list of rooms if you have shell access to the server (Docker host):
`echo 'KEYS "snapshot-*"' |  docker exec -i  redis redis-cli`
