### ISSUE TITLE
Rename spreadcheat and error with multiple users

### ISSUE THREAD

**Issue by OliverHi** [audreyt/ethercalc#207]
I have installed ethercalc via npm on a synology discstation and I have some questions/problems:

- I can import excel cheats via the landing page (which is a great feature!!) but they get assigned random urls. On the other hand I can just create a properly names cheat via calling the ...adressOfEthercalc/name adress (which is also great). How can I combine this? I want to import an excel document and give it a human readable name (meaning url).

- I have some problems with multiple users: one user can smoothly work with a document but when a second user (from another pc in the same LAN) tries to connect he just gets a loading screen forever. Once the first user closes the tab the second one can access the cheat without problems.

- Where can I find logs to see what ethercalc is doing/ where possible errors are happening?

Thanks in advance!

**Comment by audreyt** [comment]
Hi @OliverHi ,

1. Please check the "Rename sheet(s) after upload" checkbox while importing:

![2015-05-21 10 13 56](https://cloud.githubusercontent.com/assets/20723/7750437/b95b0a26-0006-11e5-9581-b036482dd924.png)

2. I'm not sure what is the issue here — What is your Node version? Is there a proxy server inbetween? Did it work with the public instance http://ethercalc.org/ ?

3. Usually EtherCalc logs to the command line (standard error).
