### ISSUE TITLE
SUMPRODUCT delivers wrong value for lines with 0

### ISSUE THREAD

**Issue by alex9434** [audreyt/ethercalc#343]
SUMPRODUCT calculates wrongly for columns with 0 value, e.g. this is calculated wrongly:
0	10
2	20
3	30
140

=SUMPRODUCT(A1:A3,B1:B3) is 140 instead of 130

Regard,
Alexander

**Comment by eddyparkinson** [comment]
This is a bug.

products[k] = (products[k] || 1) * value;

should check if products[k] is undefined - but when it is 0 it assumes undefined and sets it to 1

**Comment by alex9434** [comment]
That was also my hypothesis. Should it better set to 0 when undefined?

**Comment by eddyparkinson** [comment]
SUMPRODUCT calculates wrongly for columns with 0 value, e.g. this is calculated wrongly:
0 10
2 20
3 30
140=SUMPRODUCT(A1:A3,B1:B3) is 140 instead of 130
Is caclulated as 1* 1 * 10 +
1 * 2 * 20 +
1 * 3 * 30 +

because 0 is being changed to 1 
>That was also my hypothesis. Should it better set to 0 when undefined?Sorry, no. When it is undefined, it should be 1, but when it is 0 then it should remain 0 and not be changed to 1;



That is because the cal


  ---
Eddy Parkinson PhD
Software Engineering and Logistics
Mobile 0406 962 958 

New ideas pass through three periods: 1) It can`t be done. 2) It 
probably can be done, but it`s not worth doing. 3) I knew it was a good 
idea all along! - Arthur C. Clarke
 

    On Monday, 2 May 2016, 21:25, Alexander <notifications@github.com> wrote:
 

 That was also my hypothesis. Should it better set to 0 when undefined?—
