### ISSUE TITLE
Adjusting the start page

### ISSUE THREAD

**Issue by nebulade** [audreyt/ethercalc#402]
Hi, I am looking into improving the start page for the ethercalc Cloudron app. 
What is the recommended way to do this? Ideally it would be great to show a document listing with maybe even a way to manage (eg. delete) the previously created spreadsheets. Is this kind of usage out of scope for this repo and one should create a wrapper application instead?

Thanks.

**Comment by ocdtrekkie** [comment]
It seems sensible to me that there is a use case for a "file list" type option for cases where an EtherCalc will only be accessed by people who should be able to see all of the spreadsheets available. Though I guess the question is, would this feature "work" correctly with a standalone EtherCalc? Since EtherCalc has no authentication, if someone inadvertently turned on the file list feature, everyone public could see and edit everyone's spreadsheets, which would be bad. You'd really only want that feature in the scenario of a platform like Cloudron, where it's run in a Docker-esque container. (And since Sandstorm containerizes individual documents/spreadsheets, it wouldn't need it either.)

In the notion that the page would be pretty separate from the rest of EtherCalc's code, I think it'd be pretty ideal to keep it separate as a branch, fork, or sure, wrapper. I feel like this isn't the first time this sort of thing has been asked for though, so I think there's probably people who would benefit from it's creation.

**Comment by ocdtrekkie** [comment]
Ah, here's some responses from the maintainer about this request: #124 and #259

**Comment by eddyparkinson** [comment]
**document listing** can be done with `/_rooms` see:
https://github.com/audreyt/ethercalc/blob/master/src/main.ls#L211-L230
