### ISSUE TITLE
Q: Possible to import/export to filesystem

### ISSUE THREAD

**Issue by marks** [audreyt/ethercalc#437]
I am looking at the possibility of embedding this in another app and was wondering if there is a mode to read from disk (without upload) and save to disk (without downloading via browser).

If not - is there somewhere in the code I should start looking in order to start this extension?

**Comment by eddyparkinson** [comment]
**Server side replication**

There is a local server version of the spreadsheet. So that all client commands can be replicated on the server. This replication means that almost all to code/html that runs on the broswer also exists on the server.

**Zappa**
Another option is: zappa or express. It is built with zappa which uses express.
https://zappajs.github.io/zappajs/

Maybe they have a direct way to connect in.

**Frames**
it will run in a frame - 
http://sheet.cellmaster.com.au/carbonoffset/appeditor
