### ISSUE TITLE
Release snaps during CI steps

### ISSUE THREAD

**Issue by dholbach** [audreyt/ethercalc#449]
It'd be great to automatically push snaps to the store as part of a CI procedure:

The manual process for this involves:
- Once:
  - Register an account at http://myapps.developer.ubuntu.com/
  - Run snapcraft login
  - Run snapcraft register ethercalc
- For the release itself: snapcraft push ethercalc_<version>.snap --release=edge

I would recommend using `edge` for every rev that is built and `stable` for every stable release. That way users can go `snap install ethercalc` or `snap install ethercalc --edge` depending on their needs (the latter could be testers or people interested in the latest developments).

@evandandrea wrote up the procedure for how set things up in this post: https://lists.ubuntu.com/archives/snapcraft/2016-August/000831.html

**Comment by elopio** [comment]
Hello. I've been working with some projects to get their snaps build automatically on travis, launchpad and other CI systems. I can help here.
But in order to get the automatic push to the store, somebody from your project with the right credentials needs to do the actual steps. If you would like we could jump into a chat or hangout or something, and I can guide you, and answer any question you might have along the way.

**Comment by eddyparkinson** [comment]
@elopio Why is this not possible via a pull request?  pull requests are welcome.

**Comment by elopio** [comment]
@eddyparkinson because I don't have the credentials that are required to push ethercalc to the store. That's controlled by the person who registered the name.

**Comment by eddyparkinson** [comment]
@elopio audreyt would have created the Git Hub account. I have write access.

What is the aim with this, do you know someone who wants CI setting up for ethercalc? Happy to spend an hour helping setup if you know someone who wants it.

**Comment by elopio** [comment]
@eddyparkinson The idea is to make a release of ethercalc to the edge channel on the store every time something changes on the master branch. I am a tester in Ubuntu, and this is the most game-changing feature of snaps for me. Your community of early adopters will be happy to check the newest features, because it will be really simple. They will just have to do `$ sudo snap install ethercalc --edge` once, and their ethercalc will be autoupdated every time you make a change in master. They will give you feedback during your release cycle, and depending on the confidence and stability you have on your latest revision, you will move it from the edge channel to beta, candidate and finally stable.

All of this with really low maintenance for you. It just requires to set up travis, launchpad or any other system that will trigger events when your branch changes.

**Comment by elopio** [comment]
Ping @eddyparkinson. I'm just coming back from holidays, so please let me know when you have some time to keep talking about this.

Happy new year! :)

**Comment by popey** [comment]
Hi, is there anything blocking getting ethercalc in the snappy store? I'd love to see it in there so it's super easy to install :)

**Comment by eddyparkinson** [comment]
@popey automated tests - we don't have any automated tests, but if you want to work on it, talk to audreyt to get the authorisation setup.

**Comment by elopio** [comment]
If you don't have automated tests, that's one more reason to push the latest version every day to the edge channel and start doing crowd-testing. You will get cheap feedback that will prevent critical bugs to be released, while you invest on the automation. Just saying... ;) 

I don't have time to write the tests for you, but I have plenty of experience writing selenium tests. Let me know when you start, I'd be happy to review some code if you'd like help with that.

**Comment by elopio** [comment]
@eddyparkinson @audreyt hello again! take a look at https://build.snapcraft.io/
It's our new service for building and continuous delivery to the store. It just requires a couple of clicks to get your package set up and ready. It's in beta, so we are eager to hear about your experience there.
