### ISSUE TITLE
What is the format for the "set" command to insert dates and times into cells?

### ISSUE THREAD

**Issue by CarbonMan** [audreyt/ethercalc#471]
I have been trying to insert dates and times into cells. 
Using SocialCalc.CurrentSpreadsheetControlObject.editor.EditorScheduleSheetCommands I wish to set the date into cell A2 and the time into cell B2. 
After doing it manually and looking at the audit I have;
set A2 constant nd 42735 12/31/2016
and
set B2 constant nt 0.5208449074074074 12:30:01

What do these values mean?
Thanks.

**Comment by eddyparkinson** [comment]
>set A2 constant nd 42735 12/31/2016

nd := number date
42735 := Dates in Excel are number of days since 1/1/1900. 

>set B2 constant nt 0.5208449074074074 12:30:01

nt := number time
0.520... := 1/2 a day  or to be more exact 24*60*60/12*60*60+30*60+1 - again same as excel

date calculation
https://github.com/marcelklehr/socialcalc/blob/master/formula1.js#L3180-L3182

time calclation
https://github.com/marcelklehr/socialcalc/blob/master/formula1.js#L3208

set examples and data types
https://github.com/marcelklehr/socialcalc/blob/master/formula1.js#L5602-L5612

**Comment by CarbonMan** [comment]
Thanks heaps @eddyparkinson I'll take a look at it and update how I go.

**Comment by CarbonMan** [comment]
It works and I am a happy man :)
