### ISSUE TITLE
How to setup multi-server

### ISSUE THREAD

**Issue by brecke** [audreyt/ethercalc#673]
Hello there,

I've been integrating ethercalc with the Open Academic Environment (OAE) and I am interested in enabling multi-server mode for deployment purposes. 

It says in the README that one must use redis, but nothing else. Is there any documentation for this? where should I start?

Thanks in advance.

**Comment by eddyparkinson** [comment]
While I have not tried it. I expect all you need to do is set these

set env vars:
  REDIS_PORT REDIS_HOST REDIS_SOCKPATH REDIS_PASS REDIS_DB OPENSHIFT_DATA_DIR

Defaults:
  REDIS_HOST = localhost   
  REDIS_PORT = 6379   


But not sure what happens if two people edit the same sheet on different servers at the same time. You would need to talk to Audrey about that, I have not looked much at that section of the code. 

Zappajs
---
We use zappajs, which include multi-server

> For a multi-server / Node.js cluster example, see examples/share_*.coffee.
https://github.com/audreyt/zappajs/blob/master/examples/share_express.coffee
https://github.com/audreyt/zappajs/blob/master/examples/share_socket.coffee

from  https://github.com/audreyt/zappajs/blob/master/docs/reference.md

**Comment by eddyparkinson** [comment]
Closing issue. But let us know how you get on, thanks.
