### ISSUE TITLE
Entire Sheet Empty

### ISSUE THREAD

**Issue by mbressman** [audreyt/ethercalc#736]
Have been using EtherCalc for a few months now and so far so good (mostly - occasionally something seems to happen that causes EtherCalc to crash on the virtual server, and I have to restart the server, but that seems semi-rare).  Unfortunately the other day some users attempted to open a sheet they have been working on (and adding data to) for a month or two, and it was completely empty.  No other sheets seem to be experiencing this issue, and restarting the virtual server didn't help.  We are using Redis for the back-end, so I don't know if this indicates the dump.rdb file has become partially corrupted, or something else.  

I do have nightly backups of the dump.rdb file (as well as backups of the entire Hyper-V Ubuntu server), and tried to create a second dev instance of the Ubuntu server so I could play around with attempting to restore the missing data from some of the backups, but so far most of my attempts have failed.  It seems like when I use one of the backed-up dump.rdb files, Redis fails to load entirely.  Not sure what that means exactly.

Any help or pointers in the right direction would be extremely appreciated!  Thanks so much!

Also, on a separate note entirely - how do we check to see if there are any updates available for EtherCalc, and then how do we update EtherCalc?  Just wondering if there is a process here?

Thanks again!

**Comment by novadeviator** [comment]
We just lost  sheet on ethercalc.net we were working on for 14 days. it's simply empty. we were stupid enough to not do any export. ethercalc.net has no contact mentioned anywhere. sorry to partially highjack the thread, but it;s a similar issue.

**Comment by eddyparkinson** [comment]
Sorry for the data loss.

redis backup
---

You might be better asking Redis people about restoring from a backup. I have not seen this issue with people who use redis. 
It suggests the check to see if the sheet exists failed, so it created a blank sheet. Not sure what happens if there is a network error as the transaction task place. 

updates available for EtherCalc
---

We do update npm - there is little active development at the moment. There has not been an update in the last few months.

https://www.npmjs.com/package/ethercalc
